<main class="container">
    <div class="slider">
        <div><img src="assets/ressources/images/slider-01.jpg" alt="Table seen from the top with drinks and plates with food"></div>
        <div><img src="assets/ressources/images/slider-02.jpg" alt="Zoom on a plate seen from the top and red chilli"></div>
        <div><img src="assets/ressources/images/slider-03.jpg" alt="Table seen from the top with drinks and plates with food"></div>
    </div> <!-- end of .slider -->
    <section class="intro">
        <h1><?= htmlspecialchars($intro[0]['name']) ?></h1>
        <img src="<?= htmlspecialchars($intro[0]['src']) ?>" alt="<?= htmlspecialchars($intro[0]['alt']) ?>" class="intro-img">
        <p><?= htmlspecialchars($intro[0]['content']) ?></p>
    </section>
    <section class="menu">
        <h2>Special menus</h2>
        <?php foreach($menus as $menu): ?>
            <article>
                <h3><?= htmlspecialchars($menu['title']) ?></h3>
                <figure>
                    <img src="<?= htmlspecialchars($menu['src']) ?>" alt="<?= htmlspecialchars($menu['alt']) ?>">
                    <figcaption><?= htmlspecialchars($menu['price']) ?><br>
                        <span>soft drinks and desert included</span>
                        <span>+ taxes</span>
                    </figcaption>
                </figure>
                <ul>
                    <?php foreach($meals as $meal): ?>
                        <?php if($meal['id_category'] == $menu['id_category']): ?>
                            <li><i class="fas fa-star"></i><?= htmlspecialchars($meal['name']) ?></li>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </ul>
                <a href="index.php?page=menus" class="details"><img src="assets/ressources/images/fork-knife.svg" alt="">See more</a>
            </article>
        <?php endforeach; ?>
    </section>
</main>