<section>
	<form method="post">
		<p>
			<label for='identifiant'>Identifiant</label>
			<input type="text" name="identifiant" id="identifiant">
		</p>
		<p>
			<label for='pw'>Mot de passe</label>
			<input type="password" name="pw" id="pw">
		</p>
		<button>Se connecter</button>
		<!--<a href="index.php?page=inscription">S'inscrire ?</a>-->
		<p><strong><?= $this-> message ?></strong></p>
	</form>
</section>