<section>
	<form method="post">
		<p>
			<label for='identifiant'>Identifiant</label>
			<input type="text" name="identifiant" id="identifiant">
		</p>
		<p>
			<label for='pw'>Mot de passe</label>
			<input type="password" name="pw" id="pw">
		</p>
		<button id="adminform">Se connecter</button>
		<!--<a href="index.php?page=inscription">S'inscrire ?</a>-->
		<p class="error"><?= $this-> message ?></p>
	</form>
</section>