<table class = "menusTable" id="menusTable">
    
    <caption><strong>Gestion des Menus</strong></caption>
        <thead>
            <tr>
                <th>Id</th>
                <th>Alias</th>
                <th>Title</th>
                <th>Image</th>
                <th>Categories</th>
                <th>Price</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        
        <tbody>
            
            <?php foreach($menusTable as $menu): ?>
            
            <!-- Class Show visible de base -->
                <tr>
                
                    <td> <?= htmlspecialchars($menu['id']) ?> </td>
                    <td> <?= htmlspecialchars($menu['alias']) ?> </td>
                    <td> <?= htmlspecialchars($menu['title']) ?> </td>
                    <td> <img src="<?= htmlspecialchars($menu['src'])?>" alt ="<?= htmlspecialchars($menu['alt'])?>"> </td>
                    <td> <?= htmlspecialchars($menu['name']) ?> </td>
                    <td> <?= htmlspecialchars($menu['price']) ?> </td>
                    <!-- Boutons data id quand je clic ca affiche l'autre class -->
                    <td><button class="btn-modify" data-id="<?= $menu['id'] ?>" ><i class="fas fa-pen-nib"></i></button>
                    </td>
        	        <td><button type ="button" class ="delete-menus" data-id="<?= $menu['id'] ?>"><i class="fas fa-trash-alt"></i></button></td>
                </tr>  
            <?php endforeach; ?>
        </tbody>    
    
</table>          

<button type="button" class="add-one-menu" >Ajouter un menu</button>            
             <!-- FORMULAIRE -->
     
<form class="hide" id ="formulaire" data-id="1" method="post" enctype="multipart/form-data">
   <fieldset>
       <legend><h2>Modifier un menu</h2></legend>
        
        <div class="hide">
        <label for="id">ID</label>
        <input type="text" name ="id" value ="<?= htmlspecialchars(isset($_GET['id']) ? $editMenu['id'] : "" ) ?>" class="id-menus">
        </div>
        
        <label for="alias">Alias</label>
        <input name ="alias" type="text" value ="<?= htmlspecialchars(isset($_GET['id']) ? $editMenu['alias'] : "" ) ?>" class="alias-menus">
        
        <label for="title">Title</label>
        <input name ="title" type="text" value ="<?= htmlspecialchars(isset($_GET['id']) ? $editMenu['title'] : "" ) ?>" class="title-menus">

        <label for="image">Image</label>
        <input type="file" name="image" class="image-menus">
            <img src="<?= htmlspecialchars(isset($_GET['id']) ? $editMenu['src'] : "" ) ?>" alt ="<?= htmlspecialchars(isset($_GET['id']) ? $editMenu['alt'] : "" ) ?>">
            
        <label for="alt">Alt</label>
        <input name ="alt" type="text" value ="<?= htmlspecialchars(isset($_GET['id']) ? $editMenu['alt'] : "" ) ?>" class="alt-menus">


        <label for="categories">Categories</label>
        <select class="categories-menus" name="categories">
            <?php foreach($categories as $category): ?>
            		<option value ="<?= htmlspecialchars($category['id']) ?>"><?= htmlspecialchars($category['name']) ?>
            		</option>
            <?php endforeach; ?>		
        </select>
        
        <label for="price">Prix</label>
        <input name ="price" type="text" value ="<?= htmlspecialchars(isset($_GET['id']) ? $editMenu['price'] : "" ) ?>" class="price-menus">
    </fieldset>
<button type="button" id="add-edit" >Modifier le menu</button>

<button type="button" class="add-menus" >Ajouter le menu</button>


</form>  
        
        
 <!-- AJOUT D'UN MENUS -->
 
 
    
    
   