<section>
	<nav>
	    <ul>
	        <li><a href="">Gestion des Catégories</a></li>
	        <li><a href="">Gestion des Plats</a></li>
	        <li><a href="">Gestion du Slider</a></li>
	        <li><a href="">Gestion des Horaires</a></li>
	        <li><a href="">Gestion des Réservations</a></li>
	        <li><a href="">Gestion de l'Accueil</a></li>
	        <li><a href="">Gestion des Coordonnées</a></li>
	    </ul>
	</nav>
	<section id="gestion">
	    
	</section>
</section>