<!doctype html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Freshly Restaurant, your new favourite restaurant !">
	<title>Freshly Restaurant - Home</title>
	<link rel="icon" href="favicon.png">
	<link href="https://fonts.googleapis.com/css?family=Athiti:500|Merienda:400,700&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="assets/css/slick.css">
	<link rel="stylesheet" href="assets/css/slick-theme.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/fontawesome.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/brands.min.css">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/solid.min.css">
	<link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
	<header>
	
		<div class="container">
			<a href="index.php" class="logo">
				<img src="assets/ressources/images/logo.png" alt="Logo for Freshly Restaurant">
				<strong>Freshly Restaurant</strong>
			</a>
			<nav>
				<ul>
					<li><a href="index.php">Accueil</a></li>
					<li><a href="contact">Contact</a></li>
					<li><a href="menus">Menus</a></li>
					<?php if(isset($_SESSION['admin'])): ?>
						<li><a href="index.php?page=dashboard">Dashboard</a></li>
						<li><a href="index.php?page=admin&action=deco">Deconnexion</a></li>
					<?php else: ?>
						<li><a href="index.php?page=admin">Admin</a></li>
					<?php endif; ?>
				</ul>
			</nav>
		</div>
	</header>
	

	<!-- code principal de la page -->
	<?php include $template ?>
	
	<?php if(!isset($_COOKIE['params'])): ?>
		<section class ="cookies">
			<section class="container-cookies">
				<form id ="cookies-form"  method="post">
					<fieldset>
				       <legend><h2>Cookies</h2></legend>
			
				        <label for="cookies-fonctionnel">Acceptez vous les cookies fonctionnels</label>
				        <select class="cookies-fonctionnel" id ="cookies-fonctionnel" name="cookies-fonctionnel">
		            		<option value ="oui" selected>Oui</option>
				            <option value ="non">Non</option>	
				        </select>
				        
				        <label for="cookies-pub">Acceptez vous les cookies pub</label>
				        <select class="cookies-pub" id ="cookies-pub" name="cookies-pub">
		            		<option value ="oui" >Oui</option>
				            <option value ="non" selected>Non</option>	
				        </select>
				        
				        <label for="cookies-suivis">Acceptez vous les cookies de suivis</label>
				        <select class="cookies-suivis" id ="cookies-suivis" name="cookies-suivis">
		            		<option value ="oui">Oui</option>
				            <option value ="non" selected>Non</option>	
				        </select>
					</fieldset>
					<button type="button" id="accept-cookies" >Accepter la sélection</button>
					<button type="button" id="reject-all" >Refuser tous les cookies</button>
					<button type="button" id="accept-all" >Accepter tous les cookies</button>
				</form>
			</section>
		</section>
	<?php endif; ?>
	<footer>
		<div class="container">
			<div class="flex">
				<aside>
					<h4>Opening hours</h4>
					<ul>
						<li>Monday: Closed</li>
						<li>Tue-Wed : 9am - 10pm</li>
						<li>Thu-Fri : 9am - 10pm</li>
						<li>Sat-Sun : 5pm - 10pm</li>
					</ul>
				</aside>
				<aside>
					<h4>Contact</h4>
					<address>
						<p>13 Christopher Street<br>
							New York,<br>
							NY 10014-3543</p>
						<p>+01 2000 800 9999</p>
					</address>
				</aside>
				<aside>
					<h4>Social networks</h4>
					<div class="reseaux">
						<a href="#" class="fab fa-facebook-f"></a>
						<a href="#" class="fab fa-instagram"></a>
						<a href="#" class="fab fa-pinterest-p"></a>
					</div>
				</aside>
			</div> <!-- end of .flex -->
		</div> <!-- end of .container -->
	</footer>
	<script src="assets/js/script.js"></script>
	<script src="assets/js/slider.js"></script>
</body>



</html>
	
	
	